package com.example.ui.localization

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.getValue
import androidx.compose.runtime.staticCompositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

enum class AppLanguage(val code: String, val nativeName: String, val rtl: Boolean) {
    BN("bn", "বাংলা", false), EN("en", "English", false), HI("hi", "हिन्दी", false),
    AR("ar", "العربية", true), UR("ur", "اردو", true), ZH("zh", "中文", false), TR("tr", "Türkçe", false)
}

private val dictionaries: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.EN to emptyMap(),
    AppLanguage.BN to mapOf(
        "Language" to "ভাষা", "Invalid License Data" to "লাইসেন্সের তথ্য সঠিক নয়", "MI Unlock" to "MI Unlock", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi ও HyperOS Bootloader Utility",
        "Device ID" to "ডিভাইস আইডি", "Copy Device ID" to "ডিভাইস আইডি কপি করুন", "Authorization Required" to "অনুমোদন প্রয়োজন",
        "Admin approval is required before you can use this application. Please submit your details below." to "এই অ্যাপ ব্যবহার করতে প্রশাসকের অনুমোদন প্রয়োজন। নিচে আপনার তথ্য দিন।",
        "Full Name *" to "পূর্ণ নাম *", "Contact Number *" to "যোগাযোগ নম্বর *", "Telegram Username" to "Telegram ইউজারনেম", "WhatsApp Number" to "WhatsApp নম্বর", "Device ID (read-only)" to "ডিভাইস আইডি (শুধু পড়া যাবে)",
        "REQUEST APPROVAL" to "অনুমোদনের আবেদন", "Submitting..." to "জমা দেওয়া হচ্ছে...", "Pending Approval" to "অনুমোদনের অপেক্ষায়", "Approval Request Submitted" to "অনুমোদনের আবেদন জমা হয়েছে", "Refresh" to "রিফ্রেশ", "Check Status" to "স্ট্যাটাস দেখুন", "Edit Info" to "তথ্য সম্পাদনা", "Approval Rejected" to "অনুমোদন প্রত্যাখ্যাত", "Re-apply" to "আবার আবেদন", "License Expired" to "লাইসেন্সের মেয়াদ শেষ", "Refresh License" to "লাইসেন্স রিফ্রেশ করুন", "Device Blocked" to "ডিভাইস ব্লক করা হয়েছে", "Maintenance" to "রক্ষণাবেক্ষণ", "Maintenance Mode" to "রক্ষণাবেক্ষণ মোড", "Update Required" to "আপডেট প্রয়োজন",
        "License Details" to "লাইসেন্সের তথ্য", "License Server Configuration" to "লাইসেন্স সার্ভার কনফিগারেশন", "Save & Connect" to "সংরক্ষণ ও সংযোগ", "Reset" to "রিসেট", "Server" to "সার্ভার", "Active License" to "সক্রিয় লাইসেন্স", "Device Authorized & Active" to "ডিভাইস অনুমোদিত ও সক্রিয়", "Lifetime Access Granted" to "আজীবন অ্যাক্সেস দেওয়া হয়েছে", "Sign In with Xiaomi Account" to "Xiaomi Account দিয়ে সাইন ইন করুন", "OPEN MI ACCOUNT LOGIN" to "MI ACCOUNT LOGIN খুলুন", "Mi Account Details" to "Mi Account-এর তথ্য", "Token captured successfully" to "টোকেন সফলভাবে সংগ্রহ হয়েছে", "User ID" to "ইউজার আইডি", "Pass Token" to "Pass Token",
        "Original Output (HEX)" to "Original Output (HEX)", "Decoded Output (JSON)" to "Decoded Output (JSON)", "COPY ORIGINAL OUTPUT" to "ORIGINAL OUTPUT কপি করুন", "COPY DECODED OUTPUT" to "DECODED OUTPUT কপি করুন", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX সঠিক • ✓ DECODE সফল • ✓ JSON মিলেছে", "✗ OUTPUT VALIDATION FAILED" to "✗ OUTPUT যাচাই ব্যর্থ", "Contact Administrator" to "প্রশাসকের সাথে যোগাযোগ", "Administrator Announcement" to "প্রশাসকের ঘোষণা", "OK" to "ঠিক আছে", "Admin Contact" to "প্রশাসকের যোগাযোগ",
        "Administrator Support" to "প্রশাসক সহায়তা", "Admin Support" to "প্রশাসক সহায়তা", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Call / Phone" to "কল / ফোন", "Email" to "ইমেইল", "Copy" to "কপি", "Copied" to "কপি হয়েছে", "Sync & Verify License" to "লাইসেন্স সিঙ্ক ও যাচাই করুন", "License ID" to "লাইসেন্স আইডি", "Licensee Name" to "লাইসেন্সধারীর নাম", "Contact Phone" to "যোগাযোগ ফোন", "Activated On" to "সক্রিয় হয়েছে", "Expiration Date" to "মেয়াদ শেষের তারিখ", "Lifetime Access" to "আজীবন অ্যাক্সেস", "Active" to "সক্রিয়", "Authorized User" to "অনুমোদিত ব্যবহারকারী", "N/A" to "প্রযোজ্য নয়",
        "Name and Contact Number are required." to "নাম ও যোগাযোগ নম্বর প্রয়োজন।", "Approval request submitted" to "অনুমোদনের আবেদন জমা হয়েছে। প্রশাসকের সাথে যোগাযোগ করুন এবং অনুমোদনের অপেক্ষা করুন।", "Failed to submit request" to "আবেদন জমা দেওয়া যায়নি", "Network connection failed" to "নেটওয়ার্ক সংযোগ ব্যর্থ", "Expired access" to "অ্যাক্সেসের মেয়াদ শেষ হয়েছে", "Invalid expiration timestamp" to "মেয়াদ শেষের সময়টি সঠিক নয়", "Missing expiration timestamp" to "মেয়াদ শেষের সময় পাওয়া যায়নি", "Missing passToken" to "passToken পাওয়া যায়নি", "Missing userId" to "userId পাওয়া যায়নি", "Missing deviceId" to "deviceId পাওয়া যায়নি", "HEX encoding error" to "HEX তৈরি করতে সমস্যা হয়েছে", "HEX decoding error" to "HEX decode করতে সমস্যা হয়েছে", "UTF-8 decoding error" to "UTF-8 decode করতে সমস্যা হয়েছে"
    ),
    AppLanguage.HI to mapOf("Language" to "भाषा", "English" to "अंग्रेज़ी", "Bengali" to "बंगाली", "Hindi" to "हिन्दी", "Arabic" to "अरबी", "Urdu" to "उर्दू", "Chinese" to "चीनी", "Turkish" to "तुर्की", "Device ID" to "डिवाइस आईडी", "Authorization Required" to "अनुमोदन आवश्यक", "REQUEST APPROVAL" to "अनुमोदन अनुरोध", "Refresh" to "रीफ़्रेश", "Check Status" to "स्थिति देखें", "Device Blocked" to "डिवाइस ब्लॉक है", "License Expired" to "लाइसेंस समाप्त", "Update Required" to "अपडेट आवश्यक", "Maintenance Mode" to "रखरखाव मोड", "Sign In with Xiaomi Account" to "Xiaomi Account से साइन इन करें", "OPEN MI ACCOUNT LOGIN" to "MI ACCOUNT LOGIN खोलें", "Original Output (HEX)" to "Original Output (HEX)", "Decoded Output (JSON)" to "Decoded Output (JSON)", "COPY ORIGINAL OUTPUT" to "ORIGINAL OUTPUT कॉपी करें", "COPY DECODED OUTPUT" to "DECODED OUTPUT कॉपी करें", "Contact Administrator" to "प्रशासक से संपर्क करें", "OK" to "ठीक है", "Approval request submitted" to "अनुमोदन अनुरोध भेज दिया गया। कृपया प्रशासक से संपर्क करें और अनुमोदन की प्रतीक्षा करें।"),
    AppLanguage.AR to mapOf("Language" to "اللغة", "English" to "الإنجليزية", "Bengali" to "البنغالية", "Hindi" to "الهندية", "Arabic" to "العربية", "Urdu" to "الأردية", "Chinese" to "الصينية", "Turkish" to "التركية", "Device ID" to "معرّف الجهاز", "Authorization Required" to "الموافقة مطلوبة", "REQUEST APPROVAL" to "طلب الموافقة", "Refresh" to "تحديث", "Check Status" to "تحقق من الحالة", "Device Blocked" to "الجهاز محظور", "License Expired" to "انتهى الترخيص", "Update Required" to "التحديث مطلوب", "Maintenance Mode" to "وضع الصيانة", "Sign In with Xiaomi Account" to "تسجيل الدخول بحساب Xiaomi", "OPEN MI ACCOUNT LOGIN" to "فتح تسجيل دخول MI ACCOUNT", "Original Output (HEX)" to "الإخراج الأصلي (HEX)", "Decoded Output (JSON)" to "الإخراج المفكوك (JSON)", "COPY ORIGINAL OUTPUT" to "نسخ الإخراج الأصلي", "COPY DECODED OUTPUT" to "نسخ الإخراج المفكوك", "Contact Administrator" to "التواصل مع المسؤول", "OK" to "موافق", "Approval request submitted" to "تم إرسال طلب الموافقة. يرجى التواصل مع المسؤول وانتظار الموافقة."),
    AppLanguage.UR to mapOf("Language" to "زبان", "English" to "انگریزی", "Bengali" to "بنگالی", "Hindi" to "ہندی", "Arabic" to "عربی", "Urdu" to "اردو", "Chinese" to "چینی", "Turkish" to "ترکی", "Device ID" to "ڈیوائس آئی ڈی", "Authorization Required" to "اجازت درکار ہے", "REQUEST APPROVAL" to "منظوری کی درخواست", "Refresh" to "ریفریش", "Check Status" to "حالت دیکھیں", "Device Blocked" to "ڈیوائس بلاک ہے", "License Expired" to "لائسنس ختم ہو گیا", "Update Required" to "اپ ڈیٹ ضروری ہے", "Maintenance Mode" to "مینٹیننس موڈ", "Sign In with Xiaomi Account" to "Xiaomi Account سے سائن اِن کریں", "OPEN MI ACCOUNT LOGIN" to "MI ACCOUNT LOGIN کھولیں", "Original Output (HEX)" to "اصل آؤٹ پٹ (HEX)", "Decoded Output (JSON)" to "Decoded آؤٹ پٹ (JSON)", "COPY ORIGINAL OUTPUT" to "اصل آؤٹ پٹ کاپی کریں", "COPY DECODED OUTPUT" to "Decoded آؤٹ پٹ کاپی کریں", "Contact Administrator" to "ایڈمن سے رابطہ کریں", "OK" to "ٹھیک ہے", "Approval request submitted" to "منظوری کی درخواست جمع ہو گئی۔ ایڈمن سے رابطہ کریں اور منظوری کا انتظار کریں۔"),
    AppLanguage.ZH to mapOf("Language" to "语言", "English" to "英语", "Bengali" to "孟加拉语", "Hindi" to "印地语", "Arabic" to "阿拉伯语", "Urdu" to "乌尔都语", "Chinese" to "中文", "Turkish" to "土耳其语", "Device ID" to "设备 ID", "Authorization Required" to "需要授权", "REQUEST APPROVAL" to "申请授权", "Refresh" to "刷新", "Check Status" to "检查状态", "Device Blocked" to "设备已被阻止", "License Expired" to "许可证已过期", "Update Required" to "需要更新", "Maintenance Mode" to "维护模式", "Sign In with Xiaomi Account" to "使用 Xiaomi 账户登录", "OPEN MI ACCOUNT LOGIN" to "打开 MI 账户登录", "Original Output (HEX)" to "原始输出 (HEX)", "Decoded Output (JSON)" to "解码输出 (JSON)", "COPY ORIGINAL OUTPUT" to "复制原始输出", "COPY DECODED OUTPUT" to "复制解码输出", "Contact Administrator" to "联系管理员", "OK" to "确定", "Approval request submitted" to "授权申请已提交。请联系管理员并等待批准。"),
    AppLanguage.TR to mapOf("Language" to "Dil", "English" to "İngilizce", "Bengali" to "Bengalce", "Hindi" to "Hintçe", "Arabic" to "Arapça", "Urdu" to "Urduca", "Chinese" to "Çince", "Turkish" to "Türkçe", "Device ID" to "Cihaz Kimliği", "Authorization Required" to "Yetkilendirme Gerekli", "REQUEST APPROVAL" to "ONAY TALEP ET", "Refresh" to "Yenile", "Check Status" to "Durumu Kontrol Et", "Device Blocked" to "Cihaz Engellendi", "License Expired" to "Lisans Süresi Doldu", "Update Required" to "Güncelleme Gerekli", "Maintenance Mode" to "Bakım Modu", "Sign In with Xiaomi Account" to "Xiaomi Hesabı ile Giriş Yap", "OPEN MI ACCOUNT LOGIN" to "MI ACCOUNT GİRİŞİNİ AÇ", "Original Output (HEX)" to "Orijinal Çıktı (HEX)", "Decoded Output (JSON)" to "Çözümlenmiş Çıktı (JSON)", "COPY ORIGINAL OUTPUT" to "ORİJİNAL ÇIKTIYI KOPYALA", "COPY DECODED OUTPUT" to "ÇÖZÜMLENMİŞ ÇIKTIYI KOPYALA", "Contact Administrator" to "Yöneticiyle İletişim", "OK" to "Tamam")
)

private val fallbackTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf(
        "Active / Approved" to "সক্রিয় / অনুমোদিত", "Waiting Approval" to "অনুমোদনের অপেক্ষায়", "Request Rejected" to "আবেদন প্রত্যাখ্যাত", "Not Registered" to "নিবন্ধিত নয়", "Expiring Soon (%sd)" to "শীঘ্রই মেয়াদ শেষ (%s দিন)", "Days" to "দিন", "Hours" to "ঘণ্টা", "Minutes" to "মিনিট", "Seconds" to "সেকেন্ড", "Remaining: %s" to "অবশিষ্ট: %s", "Notes: %s" to "নোট: %s", "Reason" to "কারণ", "Expired on" to "মেয়াদ শেষ হয়েছে", "Please contact the administrator to renew your license." to "লাইসেন্স নবায়নের জন্য প্রশাসকের সাথে যোগাযোগ করুন।", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "MI Unlock-এর নতুন সংস্করণ প্রয়োজন (v%s+)। প্রশাসকের সাথে যোগাযোগ করুন বা সর্বশেষ আপডেট ডাউনলোড করুন।", "e.g. 017XXXXXXXX" to "যেমন 017XXXXXXXX", "e.g. @your_telegram" to "যেমন @your_telegram", "e.g. 01XXXXXXXXX" to "যেমন 01XXXXXXXXX", "PLEASE WAIT (%ss)..." to "অনুগ্রহ করে অপেক্ষা করুন (%s সেকেন্ড)...", "Copied" to "কপি হয়েছে", "Termux MiUnlock Payload" to "Termux MiUnlock Payload", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "হ্যালো অ্যাডমিন, MI Unlock Device ID: %s সম্পর্কে জানতে চাই।", "Approval request submitted" to "অনুমোদনের আবেদন জমা হয়েছে। প্রশাসকের সাথে যোগাযোগ করুন এবং অনুমোদনের অপেক্ষা করুন।"),
    AppLanguage.HI to mapOf(
        "Active / Approved" to "सक्रिय / अनुमोदित", "Waiting Approval" to "अनुमोदन की प्रतीक्षा", "Request Rejected" to "अनुरोध अस्वीकृत", "Not Registered" to "पंजीकृत नहीं", "Expiring Soon (%sd)" to "जल्द समाप्त (%s दिन)", "Days" to "दिन", "Hours" to "घंटे", "Minutes" to "मिनट", "Seconds" to "सेकंड", "Remaining: %s" to "शेष: %s", "Notes: %s" to "नोट: %s", "Reason" to "कारण", "Expired on" to "समाप्ति", "Please contact the administrator to renew your license." to "लाइसेंस नवीनीकरण के लिए प्रशासक से संपर्क करें।", "Copied" to "कॉपी किया गया", "Termux MiUnlock Payload" to "Termux MiUnlock Payload"
    ),
    AppLanguage.AR to mapOf(
        "Active / Approved" to "نشط / معتمد", "Waiting Approval" to "بانتظار الموافقة", "Request Rejected" to "تم رفض الطلب", "Not Registered" to "غير مسجل", "Expiring Soon (%sd)" to "ينتهي قريبًا (%s يوم)", "Days" to "يوم", "Hours" to "ساعة", "Minutes" to "دقيقة", "Seconds" to "ثانية", "Remaining: %s" to "المتبقي: %s", "Notes: %s" to "ملاحظات: %s", "Reason" to "السبب", "Expired on" to "انتهى في", "Please contact the administrator to renew your license." to "يرجى التواصل مع المسؤول لتجديد الترخيص.", "Copied" to "تم النسخ", "Termux MiUnlock Payload" to "حمولة Termux MiUnlock"
    ),
    AppLanguage.UR to mapOf(
        "Active / Approved" to "فعال / منظور شدہ", "Waiting Approval" to "منظوری کا انتظار", "Request Rejected" to "درخواست مسترد", "Not Registered" to "رجسٹرڈ نہیں", "Expiring Soon (%sd)" to "جلد ختم ہوگا (%s دن)", "Days" to "دن", "Hours" to "گھنٹے", "Minutes" to "منٹ", "Seconds" to "سیکنڈ", "Remaining: %s" to "باقی: %s", "Notes: %s" to "نوٹس: %s", "Reason" to "وجہ", "Expired on" to "میعاد ختم", "Please contact the administrator to renew your license." to "لائسنس کی تجدید کے لیے ایڈمن سے رابطہ کریں۔", "Copied" to "کاپی ہو گیا", "Termux MiUnlock Payload" to "Termux MiUnlock Payload"
    ),
    AppLanguage.ZH to mapOf(
        "Active / Approved" to "已激活 / 已批准", "Waiting Approval" to "等待批准", "Request Rejected" to "请求被拒绝", "Not Registered" to "未注册", "Expiring Soon (%sd)" to "即将到期（%s 天）", "Days" to "天", "Hours" to "小时", "Minutes" to "分钟", "Seconds" to "秒", "Remaining: %s" to "剩余：%s", "Notes: %s" to "备注：%s", "Reason" to "原因", "Expired on" to "到期时间", "Please contact the administrator to renew your license." to "请联系管理员续订许可证。", "Copied" to "已复制", "Termux MiUnlock Payload" to "Termux MiUnlock Payload"
    ),
    AppLanguage.TR to mapOf(
        "Active / Approved" to "Aktif / Onaylandı", "Waiting Approval" to "Onay Bekleniyor", "Request Rejected" to "Talep Reddedildi", "Not Registered" to "Kayıtlı Değil", "Expiring Soon (%sd)" to "Yakında Sona Eriyor (%s gün)", "Days" to "Gün", "Hours" to "Saat", "Minutes" to "Dakika", "Seconds" to "Saniye", "Remaining: %s" to "Kalan: %s", "Notes: %s" to "Notlar: %s", "Reason" to "Neden", "Expired on" to "Bitiş tarihi", "Please contact the administrator to renew your license." to "Lisansı yenilemek için yöneticiyle iletişime geçin.", "Copied" to "Kopyalandı", "Termux MiUnlock Payload" to "Termux MiUnlock Payload"
    ),
    AppLanguage.EN to emptyMap()
)

private val extendedTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf(
        "Active License" to "সক্রিয় লাইসেন্স", "Device Authorized & Active" to "ডিভাইস অনুমোদিত ও সক্রিয়", "Lifetime Access Granted" to "আজীবন অ্যাক্সেস দেওয়া হয়েছে", "Remaining: %s" to "অবশিষ্ট: %s", "Login" to "লগইন", "Sign In with Xiaomi Account" to "Xiaomi Account দিয়ে সাইন ইন করুন", "OPEN MI ACCOUNT LOGIN" to "MI ACCOUNT LOGIN খুলুন", "Mi Account Details" to "Mi Account-এর তথ্য", "Token captured successfully" to "টোকেন সফলভাবে সংগ্রহ হয়েছে", "User ID" to "ইউজার আইডি", "Pass Token" to "Pass Token", "COPY ALL FOR TERMUX" to "TERMUX-এর জন্য সব কপি করুন", "LOGOUT & SWITCH ACCOUNT" to "লগআউট ও অ্যাকাউন্ট বদলান", "License" to "লাইসেন্স", "Authorized by Telegram Administrator" to "Telegram প্রশাসক দ্বারা অনুমোদিত", "License Details" to "লাইসেন্সের তথ্য", "License ID" to "লাইসেন্স আইডি", "Licensee Name" to "লাইসেন্সধারীর নাম", "Contact Phone" to "যোগাযোগ ফোন", "Activated On" to "সক্রিয় হয়েছে", "Expiration Date" to "মেয়াদ শেষের তারিখ", "Lifetime" to "আজীবন", "Notes: %s" to "নোট: %s", "Sync & Verify License" to "লাইসেন্স সিঙ্ক ও যাচাই করুন", "License Server Configuration" to "লাইসেন্স সার্ভার কনফিগারেশন", "Configured Server URL for license authorization & Telegram bot webhook:" to "লাইসেন্স অনুমোদন ও Telegram bot webhook-এর জন্য কনফিগার করা সার্ভার URL:", "License Server Base URL" to "লাইসেন্স সার্ভারের Base URL", "Save & Connect" to "সংরক্ষণ ও সংযোগ", "Reset" to "রিসেট", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "নিরাপত্তা নোট: MI Unlock সার্ভার-নির্ভর লাইসেন্স যাচাই ব্যবহার করে। ব্যক্তিগত bot token ও credential APK-তে রাখা হয় না। ডিভাইসের সময় বা স্থানীয় preference পরিবর্তন শনাক্ত করা হয়।", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "এই ডিভাইস প্রশাসক ব্লক করেছেন। এটি ভুল হলে সাপোর্টে যোগাযোগ করুন।", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock সাময়িক রক্ষণাবেক্ষণে আছে। পরে আবার চেষ্টা করুন।", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "আপনার অনুমোদনের আবেদন জমা হয়েছে।\nপ্রশাসকের সাথে যোগাযোগ করুন এবং অনুমোদনের অপেক্ষা করুন।", "Approval Request Rejected" to "অনুমোদনের আবেদন প্রত্যাখ্যাত", "Reason" to "কারণ", "Expired on" to "মেয়াদ শেষ হয়েছে", "Please contact the administrator to renew your license." to "লাইসেন্স নবায়নের জন্য প্রশাসকের সাথে যোগাযোগ করুন।", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "MI Unlock-এর নতুন সংস্করণ প্রয়োজন (v%s+)। প্রশাসকের সাথে যোগাযোগ করুন বা সর্বশেষ আপডেট ডাউনলোড করুন।"
    ),
    AppLanguage.HI to mapOf(
        "Active License" to "सक्रिय लाइसेंस", "Device Authorized & Active" to "डिवाइस अधिकृत और सक्रिय", "Lifetime Access Granted" to "लाइफटाइम एक्सेस दिया गया", "Remaining: %s" to "शेष: %s", "Login" to "लॉगिन", "Mi Account Details" to "Mi Account विवरण", "Token captured successfully" to "टोकन सफलतापूर्वक प्राप्त हुआ", "User ID" to "यूज़र आईडी", "Pass Token" to "Pass Token", "COPY ALL FOR TERMUX" to "TERMUX के लिए सब कॉपी करें", "LOGOUT & SWITCH ACCOUNT" to "लॉगआउट और अकाउंट बदलें", "License" to "लाइसेंस", "Authorized by Telegram Administrator" to "Telegram प्रशासक द्वारा अधिकृत", "License ID" to "लाइसेंस आईडी", "Licensee Name" to "लाइसेंसधारी का नाम", "Contact Phone" to "संपर्क फोन", "Activated On" to "सक्रिय किया गया", "Expiration Date" to "समाप्ति तिथि", "Lifetime" to "लाइफटाइम", "Notes: %s" to "नोट: %s", "Sync & Verify License" to "लाइसेंस सिंक और सत्यापित करें", "License Server Configuration" to "लाइसेंस सर्वर कॉन्फ़िगरेशन", "Save & Connect" to "सहेजें और कनेक्ट करें", "Reset" to "रीसेट", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "इस डिवाइस को प्रशासक ने ब्लॉक किया है। यदि यह गलत है तो सहायता से संपर्क करें।", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock अस्थायी रूप से रखरखाव में है। बाद में पुनः प्रयास करें।", "Approval Request Rejected" to "अनुमोदन अनुरोध अस्वीकृत", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "आपका अनुमोदन अनुरोध भेज दिया गया है।\nप्रशासक से संपर्क करें और अनुमोदन की प्रतीक्षा करें।", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "MI Unlock का नया संस्करण आवश्यक है (v%s+)। प्रशासक से संपर्क करें या नवीनतम अपडेट डाउनलोड करें।"
    ),
    AppLanguage.AR to mapOf(
        "Active License" to "ترخيص نشط", "Device Authorized & Active" to "الجهاز مصرح ونشط", "Lifetime Access Granted" to "تم منح وصول مدى الحياة", "Remaining: %s" to "المتبقي: %s", "Login" to "تسجيل الدخول", "Mi Account Details" to "تفاصيل حساب Mi", "Token captured successfully" to "تم التقاط الرمز بنجاح", "User ID" to "معرّف المستخدم", "Pass Token" to "رمز Pass", "COPY ALL FOR TERMUX" to "نسخ الكل لـ Termux", "LOGOUT & SWITCH ACCOUNT" to "تسجيل الخروج وتبديل الحساب", "License" to "الترخيص", "Authorized by Telegram Administrator" to "مصرح به من مسؤول Telegram", "License ID" to "معرّف الترخيص", "Licensee Name" to "اسم صاحب الترخيص", "Contact Phone" to "هاتف الاتصال", "Activated On" to "تم التفعيل في", "Expiration Date" to "تاريخ الانتهاء", "Lifetime" to "مدى الحياة", "Notes: %s" to "ملاحظات: %s", "Sync & Verify License" to "مزامنة والتحقق من الترخيص", "License Server Configuration" to "إعداد خادم الترخيص", "Save & Connect" to "حفظ واتصال", "Reset" to "إعادة تعيين", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "تم حظر هذا الجهاز من قبل المسؤول. تواصل مع الدعم إذا كان ذلك خطأ.", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock قيد الصيانة مؤقتًا. يرجى المحاولة لاحقًا.", "Approval Request Rejected" to "تم رفض طلب الموافقة", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "تم إرسال طلب الموافقة.\nيرجى التواصل مع المسؤول وانتظار الموافقة.", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "يلزم إصدار أحدث من MI Unlock (v%s+). يرجى التواصل مع المسؤول أو تنزيل آخر تحديث."
    ),
    AppLanguage.UR to mapOf(
        "Active License" to "فعال لائسنس", "Device Authorized & Active" to "ڈیوائس منظور شدہ اور فعال", "Lifetime Access Granted" to "تاحیات رسائی دی گئی", "Remaining: %s" to "باقی: %s", "Login" to "لاگ اِن", "Mi Account Details" to "Mi Account کی تفصیلات", "Token captured successfully" to "ٹوکن کامیابی سے حاصل ہو گیا", "User ID" to "یوزر آئی ڈی", "Pass Token" to "Pass Token", "COPY ALL FOR TERMUX" to "TERMUX کے لیے سب کاپی کریں", "LOGOUT & SWITCH ACCOUNT" to "لاگ آؤٹ اور اکاؤنٹ تبدیل کریں", "License" to "لائسنس", "Authorized by Telegram Administrator" to "Telegram ایڈمن کی طرف سے منظور شدہ", "License ID" to "لائسنس آئی ڈی", "Licensee Name" to "لائسنس ہولڈر کا نام", "Contact Phone" to "رابطہ فون", "Activated On" to "فعال ہونے کا وقت", "Expiration Date" to "میعاد ختم ہونے کی تاریخ", "Lifetime" to "تاحیات", "Notes: %s" to "نوٹس: %s", "Sync & Verify License" to "لائسنس سنک اور تصدیق کریں", "License Server Configuration" to "لائسنس سرور کنفیگریشن", "Save & Connect" to "محفوظ کریں اور منسلک کریں", "Reset" to "ری سیٹ", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "اس ڈیوائس کو ایڈمن نے بلاک کیا ہے۔ اگر یہ غلطی ہے تو سپورٹ سے رابطہ کریں۔", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock عارضی طور پر مینٹیننس میں ہے۔ بعد میں دوبارہ کوشش کریں۔", "Approval Request Rejected" to "منظوری کی درخواست مسترد", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "آپ کی منظوری کی درخواست جمع ہو گئی ہے۔\nایڈمن سے رابطہ کریں اور منظوری کا انتظار کریں۔", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "MI Unlock کا نیا ورژن درکار ہے (v%s+)۔ ایڈمن سے رابطہ کریں یا تازہ ترین اپ ڈیٹ ڈاؤن لوڈ کریں۔"
    ),
    AppLanguage.ZH to mapOf(
        "Active License" to "有效许可证", "Device Authorized & Active" to "设备已授权并激活", "Lifetime Access Granted" to "已授予永久访问权限", "Remaining: %s" to "剩余：%s", "Login" to "登录", "Mi Account Details" to "Mi 账户详情", "Token captured successfully" to "令牌获取成功", "User ID" to "用户 ID", "Pass Token" to "Pass Token", "COPY ALL FOR TERMUX" to "复制全部用于 Termux", "LOGOUT & SWITCH ACCOUNT" to "退出并切换账户", "License" to "许可证", "Authorized by Telegram Administrator" to "由 Telegram 管理员授权", "License ID" to "许可证 ID", "Licensee Name" to "许可证用户姓名", "Contact Phone" to "联系电话", "Activated On" to "激活时间", "Expiration Date" to "到期日期", "Lifetime" to "永久", "Notes: %s" to "备注：%s", "Sync & Verify License" to "同步并验证许可证", "License Server Configuration" to "许可证服务器配置", "Save & Connect" to "保存并连接", "Reset" to "重置", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "此设备已被管理员阻止。如有误，请联系支持。", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock 正在维护中，请稍后再试。", "Approval Request Rejected" to "授权申请被拒绝", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "授权申请已提交。\n请联系管理员并等待批准。", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "需要新版 MI Unlock（v%s+）。请联系管理员或下载最新更新。"
    ),
    AppLanguage.TR to mapOf(
        "Active License" to "Aktif Lisans", "Device Authorized & Active" to "Cihaz Yetkili ve Aktif", "Lifetime Access Granted" to "Ömür Boyu Erişim Verildi", "Remaining: %s" to "Kalan: %s", "Login" to "Giriş", "Mi Account Details" to "Mi Hesap Detayları", "Token captured successfully" to "Token başarıyla alındı", "User ID" to "Kullanıcı Kimliği", "Pass Token" to "Pass Token", "COPY ALL FOR TERMUX" to "TERMUX İÇİN TÜMÜNÜ KOPYALA", "LOGOUT & SWITCH ACCOUNT" to "ÇIKIŞ YAP VE HESAP DEĞİŞTİR", "License" to "Lisans", "Authorized by Telegram Administrator" to "Telegram yöneticisi tarafından yetkilendirildi", "License ID" to "Lisans Kimliği", "Licensee Name" to "Lisans Sahibi", "Contact Phone" to "İletişim Telefonu", "Activated On" to "Etkinleştirme", "Expiration Date" to "Son Kullanma Tarihi", "Lifetime" to "Ömür Boyu", "Notes: %s" to "Notlar: %s", "Sync & Verify License" to "Lisansı Senkronize Et ve Doğrula", "License Server Configuration" to "Lisans Sunucusu Yapılandırması", "Save & Connect" to "Kaydet ve Bağlan", "Reset" to "Sıfırla", "This device has been blocked by the administrator. Contact support if you believe this is an error." to "Bu cihaz yönetici tarafından engellendi. Hata olduğunu düşünüyorsanız destekle iletişime geçin.", "MI Unlock is temporarily under maintenance. Please try again later." to "MI Unlock geçici olarak bakımda. Lütfen daha sonra tekrar deneyin.", "Approval Request Rejected" to "Onay Talebi Reddedildi", "Your approval request has been submitted.\nPlease contact the administrator and wait for approval." to "Onay talebiniz gönderildi.\nYöneticiyle iletişime geçin ve onayı bekleyin.", "A newer version of MI Unlock is required (v%s+). Please contact the administrator or download the latest update." to "MI Unlock'un daha yeni bir sürümü gerekli (v%s+). Yöneticiyle iletişime geçin veya son güncellemeyi indirin."
    ),
    AppLanguage.HI to emptyMap()
)

private val uiTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf("MI Unlock Tool" to "MI Unlock Tool", "Announcement" to "ঘোষণা", "Administrator Announcement" to "প্রশাসকের ঘোষণা", "Contact Administrator" to "প্রশাসকের সাথে যোগাযোগ", "Close" to "বন্ধ করুন", "Admin Contact" to "প্রশাসকের যোগাযোগ", "Refresh" to "রিফ্রেশ", "Admin Support" to "প্রশাসক সহায়তা", "Administrator Support" to "প্রশাসক সহায়তা", "Contact for license activation, renewal & inquiries" to "লাইসেন্স সক্রিয়করণ, নবায়ন ও তথ্যের জন্য যোগাযোগ করুন", "Telegram username" to "Telegram ইউজারনেম", "WhatsApp number" to "WhatsApp নম্বর", "Call / Phone" to "কল / ফোন", "Contact number" to "যোগাযোগ নম্বর", "Admin email" to "প্রশাসকের ইমেইল", "Call" to "কল", "Copy" to "কপি", "Copied" to "কপি হয়েছে"),
    AppLanguage.HI to mapOf("MI Unlock Tool" to "MI Unlock Tool", "Announcement" to "घोषणा", "Administrator Announcement" to "प्रशासक की घोषणा", "Contact Administrator" to "प्रशासक से संपर्क करें", "Close" to "बंद करें", "Admin Contact" to "प्रशासक संपर्क", "Refresh" to "रीफ़्रेश", "Admin Support" to "प्रशासक सहायता", "Administrator Support" to "प्रशासक सहायता", "Contact for license activation, renewal & inquiries" to "लाइसेंस सक्रियण, नवीनीकरण और पूछताछ के लिए संपर्क करें", "Telegram username" to "Telegram यूज़रनेम", "WhatsApp number" to "WhatsApp नंबर", "Call / Phone" to "कॉल / फोन", "Contact number" to "संपर्क नंबर", "Admin email" to "प्रशासक ईमेल", "Call" to "कॉल", "Copy" to "कॉपी", "Copied" to "कॉपी किया गया"),
    AppLanguage.AR to mapOf("MI Unlock Tool" to "أداة MI Unlock", "Announcement" to "إعلان", "Administrator Announcement" to "إعلان المسؤول", "Contact Administrator" to "التواصل مع المسؤول", "Close" to "إغلاق", "Admin Contact" to "اتصال المسؤول", "Refresh" to "تحديث", "Admin Support" to "دعم المسؤول", "Administrator Support" to "دعم المسؤول", "Contact for license activation, renewal & inquiries" to "للتواصل بشأن تفعيل الترخيص وتجديده والاستفسارات", "Telegram username" to "اسم مستخدم Telegram", "WhatsApp number" to "رقم WhatsApp", "Call / Phone" to "اتصال / هاتف", "Contact number" to "رقم الاتصال", "Admin email" to "بريد المسؤول", "Call" to "اتصال", "Copy" to "نسخ", "Copied" to "تم النسخ"),
    AppLanguage.UR to mapOf("MI Unlock Tool" to "MI Unlock Tool", "Announcement" to "اعلان", "Administrator Announcement" to "ایڈمن کا اعلان", "Contact Administrator" to "ایڈمن سے رابطہ کریں", "Close" to "بند کریں", "Admin Contact" to "ایڈمن رابطہ", "Refresh" to "ریفریش", "Admin Support" to "ایڈمن سپورٹ", "Administrator Support" to "ایڈمن سپورٹ", "Contact for license activation, renewal & inquiries" to "لائسنس ایکٹیویشن، تجدید اور معلومات کے لیے رابطہ کریں", "Telegram username" to "Telegram یوزرنیم", "WhatsApp number" to "WhatsApp نمبر", "Call / Phone" to "کال / فون", "Contact number" to "رابطہ نمبر", "Admin email" to "ایڈمن ای میل", "Call" to "کال", "Copy" to "کاپی", "Copied" to "کاپی ہو گیا"),
    AppLanguage.ZH to mapOf("MI Unlock Tool" to "MI Unlock 工具", "Announcement" to "公告", "Administrator Announcement" to "管理员公告", "Contact Administrator" to "联系管理员", "Close" to "关闭", "Admin Contact" to "管理员联系方式", "Refresh" to "刷新", "Admin Support" to "管理员支持", "Administrator Support" to "管理员支持", "Contact for license activation, renewal & inquiries" to "许可证激活、续订和咨询请联系管理员", "Telegram username" to "Telegram 用户名", "WhatsApp number" to "WhatsApp 号码", "Call / Phone" to "电话", "Contact number" to "联系电话", "Admin email" to "管理员邮箱", "Call" to "呼叫", "Copy" to "复制", "Copied" to "已复制"),
    AppLanguage.TR to mapOf("MI Unlock Tool" to "MI Unlock Aracı", "Announcement" to "Duyuru", "Administrator Announcement" to "Yönetici Duyurusu", "Contact Administrator" to "Yöneticiyle İletişim", "Close" to "Kapat", "Admin Contact" to "Yönetici İletişimi", "Refresh" to "Yenile", "Admin Support" to "Yönetici Desteği", "Administrator Support" to "Yönetici Desteği", "Contact for license activation, renewal & inquiries" to "Lisans etkinleştirme, yenileme ve sorular için iletişim", "Telegram username" to "Telegram kullanıcı adı", "WhatsApp number" to "WhatsApp numarası", "Call / Phone" to "Arama / Telefon", "Contact number" to "İletişim numarası", "Admin email" to "Yönetici e-postası", "Call" to "Ara", "Copy" to "Kopyala", "Copied" to "Kopyalandı"),
    AppLanguage.EN to emptyMap()
)

private val completenessTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf(
        "Pending Approval" to "অনুমোদনের অপেক্ষায়", "Re-apply" to "আবার আবেদন", "Refresh License" to "লাইসেন্স রিফ্রেশ করুন", "Server" to "সার্ভার", "Submitting..." to "জমা দেওয়া হচ্ছে...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi ও HyperOS Bootloader Utility", "e.g. 017XXXXXXXX" to "যেমন 017XXXXXXXX", "e.g. 01XXXXXXXXX" to "যেমন 01XXXXXXXXX", "e.g. @your_telegram" to "যেমন @your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX সঠিক • ✓ DECODE সফল • ✓ JSON মিলেছে", "✗ OUTPUT VALIDATION FAILED" to "✗ OUTPUT যাচাই ব্যর্থ", "PLEASE WAIT (%ss)..." to "অনুগ্রহ করে অপেক্ষা করুন (%s সেকেন্ড)...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "নিরাপত্তা বিজ্ঞপ্তি: MI Unlock সার্ভার-নির্ধারিত লাইসেন্স যাচাই ব্যবহার করে। ব্যক্তিগত bot token ও credential এই APK-তে সংরক্ষণ করা হয় না। ডিভাইসের ঘড়ি বা স্থানীয় preference পরিবর্তন শনাক্ত করা হয়।"
    ),
    AppLanguage.HI to mapOf(
        "Pending Approval" to "अनुमोदन लंबित", "Re-apply" to "पुनः आवेदन", "Refresh License" to "लाइसेंस रीफ़्रेश करें", "Server" to "सर्वर", "Submitting..." to "जमा किया जा रहा है...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi और HyperOS Bootloader Utility", "e.g. 017XXXXXXXX" to "उदा. 017XXXXXXXX", "e.g. 01XXXXXXXXX" to "उदा. 01XXXXXXXXX", "e.g. @your_telegram" to "उदा. @your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX मान्य • ✓ डिकोड सफल • ✓ JSON मेल खाता है", "✗ OUTPUT VALIDATION FAILED" to "✗ आउटपुट सत्यापन विफल", "PLEASE WAIT (%ss)..." to "कृपया प्रतीक्षा करें (%s सेकंड)...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "सुरक्षा सूचना: MI Unlock सर्वर-आधारित लाइसेंस सत्यापन का उपयोग करता है। निजी bot token और credential इस APK में संग्रहीत नहीं होते। डिवाइस घड़ी या स्थानीय preference में छेड़छाड़ का पता लगाया जाता है।"
    ),
    AppLanguage.AR to mapOf(
        "Pending Approval" to "الموافقة قيد الانتظار", "Re-apply" to "إعادة التقديم", "Refresh License" to "تحديث الترخيص", "Server" to "الخادم", "Submitting..." to "جارٍ الإرسال...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "أداة Xiaomi وHyperOS لإلغاء قفل محمل الإقلاع", "e.g. 017XXXXXXXX" to "مثال: 017XXXXXXXX", "e.g. 01XXXXXXXXX" to "مثال: 01XXXXXXXXX", "e.g. @your_telegram" to "مثال: @your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX صالح • ✓ فك الترميز ناجح • ✓ تطابق JSON", "✗ OUTPUT VALIDATION FAILED" to "✗ فشل التحقق من الإخراج", "PLEASE WAIT (%ss)..." to "يرجى الانتظار (%s ثوانٍ)...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "إشعار أمني: يستخدم MI Unlock التحقق من الترخيص من الخادم. لا يتم تخزين رموز bot أو بيانات الاعتماد الخاصة في APK. يتم اكتشاف العبث بساعة الجهاز أو التفضيلات المحلية."
    ),
    AppLanguage.UR to mapOf(
        "Pending Approval" to "منظوری زیر التوا ہے", "Re-apply" to "دوبارہ درخواست دیں", "Refresh License" to "لائسنس ریفریش کریں", "Server" to "سرور", "Submitting..." to "جمع کیا جا رہا ہے...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi اور HyperOS بوٹ لوڈر یوٹیلیٹی", "e.g. 017XXXXXXXX" to "مثلاً 017XXXXXXXX", "e.g. 01XXXXXXXXX" to "مثلاً 01XXXXXXXXX", "e.g. @your_telegram" to "مثلاً @your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX درست • ✓ ڈی کوڈ کامیاب • ✓ JSON مماثل", "✗ OUTPUT VALIDATION FAILED" to "✗ آؤٹ پٹ کی توثیق ناکام", "PLEASE WAIT (%ss)..." to "براہِ کرم انتظار کریں (%s سیکنڈ)...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "سیکیورٹی اطلاع: MI Unlock سرور کی بنیاد پر لائسنس کی تصدیق کرتا ہے۔ نجی bot token اور credential اس APK میں محفوظ نہیں کیے جاتے۔ ڈیوائس کی گھڑی یا مقامی preference میں چھیڑ چھاڑ کا پتہ چلایا جاتا ہے۔"
    ),
    AppLanguage.ZH to mapOf(
        "Pending Approval" to "等待授权", "Re-apply" to "重新申请", "Refresh License" to "刷新许可证", "Server" to "服务器", "Submitting..." to "正在提交...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi 与 HyperOS Bootloader 工具", "e.g. 017XXXXXXXX" to "例如：017XXXXXXXX", "e.g. 01XXXXXXXXX" to "例如：01XXXXXXXXX", "e.g. @your_telegram" to "例如：@your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX 有效 • ✓ 解码成功 • ✓ JSON 匹配", "✗ OUTPUT VALIDATION FAILED" to "✗ 输出验证失败", "PLEASE WAIT (%ss)..." to "请稍候（%s 秒）...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "安全提示：MI Unlock 使用服务器权威的许可证验证。私人 bot token 和凭据不会存储在此 APK 中。系统会检测设备时钟或本地偏好的篡改。"
    ),
    AppLanguage.TR to mapOf(
        "Pending Approval" to "Onay Bekliyor", "Re-apply" to "Yeniden Başvur", "Refresh License" to "Lisansı Yenile", "Server" to "Sunucu", "Submitting..." to "Gönderiliyor...", "Telegram" to "Telegram", "WhatsApp" to "WhatsApp", "Xiaomi & HyperOS Bootloader Utility" to "Xiaomi ve HyperOS Bootloader Aracı", "e.g. 017XXXXXXXX" to "örn. 017XXXXXXXX", "e.g. 01XXXXXXXXX" to "örn. 01XXXXXXXXX", "e.g. @your_telegram" to "örn. @your_telegram", "✓ HEX VALID • ✓ DECODE SUCCESSFUL • ✓ JSON MATCH" to "✓ HEX GEÇERLİ • ✓ ÇÖZÜMLEME BAŞARILI • ✓ JSON EŞLEŞTİ", "✗ OUTPUT VALIDATION FAILED" to "✗ ÇIKTI DOĞRULAMASI BAŞARISIZ", "PLEASE WAIT (%ss)..." to "Lütfen bekleyin (%s saniye)...", "Security notice: MI Unlock uses server-authoritative license verification. Private bot tokens and credentials are never stored in this APK. Tampering with device clocks or local preferences is strictly detected." to "Güvenlik bildirimi: MI Unlock sunucu yetkili lisans doğrulaması kullanır. Özel bot tokenları ve kimlik bilgileri bu APK'da saklanmaz. Cihaz saati veya yerel tercihlerin değiştirilmesi tespit edilir."
    ),
    AppLanguage.EN to emptyMap()
)

private val additionalUiTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "আপনার অনুমোদনের আবেদন জমা হয়েছে।\\nপ্রশাসকের সাথে যোগাযোগ করুন এবং অনুমোদনের অপেক্ষা করুন।",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "Bootloader unlock-এর জন্য প্রয়োজনীয় Unlock Token (passToken, userId, deviceId) সংগ্রহ করতে আপনার Xiaomi / Mi Account-এ লগইন করুন।",
        "Cannot open WhatsApp" to "WhatsApp খোলা যাচ্ছে না", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "হ্যালো অ্যাডমিন, MI Unlock Device ID: %s সম্পর্কে জানতে চাই", "Hello Admin, MI Unlock ID: %s" to "হ্যালো অ্যাডমিন, MI Unlock ID: %s", "MI Unlock License Request" to "MI Unlock লাইসেন্সের অনুরোধ", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "হ্যালো অ্যাডমিন,\n\nMI Unlock লাইসেন্সে সহায়তা প্রয়োজন।\nDevice ID: %s\n", "Cannot launch dialer" to "ডায়ালার চালু করা যাচ্ছে না", "Cannot open email client" to "ইমেইল ক্লায়েন্ট খোলা যাচ্ছে না", "copied to clipboard" to "ক্লিপবোর্ডে কপি হয়েছে"
    ),
    AppLanguage.HI to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "आपका अनुमोदन अनुरोध भेज दिया गया है।\\nकृपया प्रशासक से संपर्क करें और अनुमोदन की प्रतीक्षा करें।",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "बूटलोडर अनलॉक के लिए आवश्यक Unlock Token (passToken, userId, deviceId) प्राप्त करने के लिए अपने Xiaomi / Mi Account में लॉग इन करें।",
        "Cannot open WhatsApp" to "WhatsApp नहीं खोला जा सका", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "नमस्ते एडमिन, MI Unlock Device ID: %s के बारे में जानकारी चाहिए", "Hello Admin, MI Unlock ID: %s" to "नमस्ते एडमिन, MI Unlock ID: %s", "MI Unlock License Request" to "MI Unlock लाइसेंस अनुरोध", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "नमस्ते एडमिन,\n\nमुझे MI Unlock लाइसेंस में सहायता चाहिए।\nDevice ID: %s\n", "Cannot launch dialer" to "डायलर शुरू नहीं किया जा सका", "Cannot open email client" to "ईमेल क्लाइंट नहीं खोला जा सका", "copied to clipboard" to "क्लिपबोर्ड पर कॉपी किया गया"
    ),
    AppLanguage.AR to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "تم إرسال طلب الموافقة.\\nيرجى التواصل مع المسؤول وانتظار الموافقة.",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "سجّل الدخول إلى حساب Xiaomi / Mi للحصول على Unlock Token (passToken, userId, deviceId) المطلوب لفتح محمل الإقلاع.",
        "Cannot open WhatsApp" to "تعذر فتح WhatsApp", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "مرحباً مسؤول النظام، أريد الاستفسار عن MI Unlock Device ID: %s", "Hello Admin, MI Unlock ID: %s" to "مرحباً مسؤول النظام، MI Unlock ID: %s", "MI Unlock License Request" to "طلب ترخيص MI Unlock", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "مرحباً مسؤول النظام،\n\nأحتاج إلى مساعدة بشأن ترخيص MI Unlock.\nمعرّف الجهاز: %s\n", "Cannot launch dialer" to "تعذر تشغيل لوحة الاتصال", "Cannot open email client" to "تعذر فتح تطبيق البريد الإلكتروني", "copied to clipboard" to "تم النسخ إلى الحافظة"
    ),
    AppLanguage.UR to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "آپ کی منظوری کی درخواست جمع ہو گئی ہے۔\\nبراہِ کرم ایڈمن سے رابطہ کریں اور منظوری کا انتظار کریں۔",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "بوٹ لوڈر ان لاک کے لیے درکار Unlock Token (passToken, userId, deviceId) حاصل کرنے کے لیے اپنے Xiaomi / Mi Account میں لاگ اِن کریں۔",
        "Cannot open WhatsApp" to "WhatsApp نہیں کھولا جا سکا", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "السلام علیکم ایڈمن، MI Unlock Device ID: %s کے بارے میں معلومات چاہیے", "Hello Admin, MI Unlock ID: %s" to "السلام علیکم ایڈمن، MI Unlock ID: %s", "MI Unlock License Request" to "MI Unlock لائسنس درخواست", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "السلام علیکم ایڈمن،\n\nمجھے MI Unlock لائسنس کے لیے مدد چاہیے۔\nDevice ID: %s\n", "Cannot launch dialer" to "ڈائلر شروع نہیں کیا جا سکا", "Cannot open email client" to "ای میل کلائنٹ نہیں کھولا جا سکا", "copied to clipboard" to "کلپ بورڈ پر کاپی ہو گیا"
    ),
    AppLanguage.ZH to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "您的授权申请已提交。\\n请联系管理员并等待批准。",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "登录您的 Xiaomi / Mi Account，以获取解锁 Bootloader 所需的 Unlock Token (passToken, userId, deviceId)。",
        "Cannot open WhatsApp" to "无法打开 WhatsApp", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "管理员您好，我想咨询 MI Unlock Device ID：%s", "Hello Admin, MI Unlock ID: %s" to "管理员您好，MI Unlock ID：%s", "MI Unlock License Request" to "MI Unlock 许可证申请", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "管理员您好，\n\n我需要获得 MI Unlock 许可证方面的帮助。\n设备 ID：%s\n", "Cannot launch dialer" to "无法启动拨号器", "Cannot open email client" to "无法打开邮件客户端", "copied to clipboard" to "已复制到剪贴板"
    ),
    AppLanguage.TR to mapOf(
        "Your approval request has been submitted.\\nPlease contact the administrator and wait for approval." to "Onay talebiniz gönderildi.\\nLütfen yöneticiyle iletişime geçin ve onayı bekleyin.",
        "Log into your Xiaomi / Mi Account to capture the Unlock Token (passToken, userId, deviceId) required for bootloader unlocking." to "Bootloader kilidini açmak için gereken Unlock Token'ı (passToken, userId, deviceId) almak üzere Xiaomi / Mi Account hesabınıza giriş yapın.",
        "Cannot open WhatsApp" to "WhatsApp açılamadı", "Hello Admin, inquiry for MI Unlock Device ID: %s" to "Merhaba yönetici, MI Unlock Device ID: %s hakkında bilgi almak istiyorum", "Hello Admin, MI Unlock ID: %s" to "Merhaba yönetici, MI Unlock ID: %s", "MI Unlock License Request" to "MI Unlock Lisans Talebi", "Hello Admin,\n\nI need assistance with my MI Unlock license.\nDevice ID: %s\n" to "Merhaba yönetici,\n\nMI Unlock lisansım için yardıma ihtiyacım var.\nCihaz ID: %s\n", "Cannot launch dialer" to "Arama ekranı başlatılamadı", "Cannot open email client" to "E-posta istemcisi açılamadı", "copied to clipboard" to "panoya kopyalandı"
    ),
    AppLanguage.EN to emptyMap()
)

private val processingErrorTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf("Invalid JSON" to "JSON সঠিক নয়", "HEX encoding error" to "HEX তৈরি করতে সমস্যা হয়েছে"),
    AppLanguage.HI to mapOf("Invalid JSON" to "अमान्य JSON", "HEX encoding error" to "HEX बनाने में त्रुटि"),
    AppLanguage.AR to mapOf("Invalid JSON" to "JSON غير صالح", "HEX encoding error" to "خطأ في ترميز HEX"),
    AppLanguage.UR to mapOf("Invalid JSON" to "غلط JSON", "HEX encoding error" to "HEX انکوڈنگ میں خرابی"),
    AppLanguage.ZH to mapOf("Invalid JSON" to "JSON 无效", "HEX encoding error" to "HEX 编码错误"),
    AppLanguage.TR to mapOf("Invalid JSON" to "Geçersiz JSON", "HEX encoding error" to "HEX kodlama hatası"),
    AppLanguage.EN to emptyMap()
)

private val commonErrorTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf("Invalid License Data" to "লাইসেন্সের তথ্য সঠিক নয়", "Invalid expiration timestamp" to "মেয়াদ শেষের সময়টি সঠিক নয়", "Missing expiration timestamp" to "মেয়াদ শেষের সময় পাওয়া যায়নি"),
    AppLanguage.HI to mapOf("Invalid License Data" to "लाइसेंस डेटा अमान्य है", "Invalid expiration timestamp" to "समाप्ति समय अमान्य है", "Missing expiration timestamp" to "समाप्ति समय उपलब्ध नहीं है"),
    AppLanguage.AR to mapOf("Invalid License Data" to "بيانات الترخيص غير صالحة", "Invalid expiration timestamp" to "وقت الانتهاء غير صالح", "Missing expiration timestamp" to "وقت الانتهاء مفقود"),
    AppLanguage.UR to mapOf("Invalid License Data" to "لائسنس کی معلومات درست نہیں", "Invalid expiration timestamp" to "میعاد ختم ہونے کا وقت درست نہیں", "Missing expiration timestamp" to "میعاد ختم ہونے کا وقت موجود نہیں"),
    AppLanguage.ZH to mapOf("Invalid License Data" to "许可证数据无效", "Invalid expiration timestamp" to "到期时间无效", "Missing expiration timestamp" to "缺少到期时间"),
    AppLanguage.TR to mapOf("Invalid License Data" to "Geçersiz Lisans Verisi", "Invalid expiration timestamp" to "Geçersiz sona erme zamanı", "Missing expiration timestamp" to "Sona erme zamanı eksik"),
    AppLanguage.EN to emptyMap(), AppLanguage.HI to emptyMap()
)

private val finalTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf("Applicant" to "আবেদনকারী", "MI Unlock Security" to "MI Unlock নিরাপত্তা"),
    AppLanguage.HI to mapOf("Applicant" to "आवेदक", "MI Unlock Security" to "MI Unlock सुरक्षा"),
    AppLanguage.AR to mapOf("Applicant" to "المتقدم", "MI Unlock Security" to "أمان MI Unlock"),
    AppLanguage.UR to mapOf("Applicant" to "درخواست گزار", "MI Unlock Security" to "MI Unlock سیکیورٹی"),
    AppLanguage.ZH to mapOf("Applicant" to "申请人", "MI Unlock Security" to "MI Unlock 安全"),
    AppLanguage.TR to mapOf("Applicant" to "Başvuran", "MI Unlock Security" to "MI Unlock Güvenliği"),
    AppLanguage.EN to emptyMap()
)

private val completeTranslations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.BN to mapOf(
        "Contact" to "যোগাযোগ", "Decoded Output" to "Decoded Output", "Original Output" to "Original Output"
    ),
    AppLanguage.HI to mapOf(
        "Active" to "सक्रिय", "Admin approval is required before you can use this application. Please submit your details below." to "इस ऐप का उपयोग करने से पहले प्रशासक की अनुमति आवश्यक है। नीचे अपना विवरण दें।", "Approval Rejected" to "अनुमोदन अस्वीकृत", "Approval Request Submitted" to "अनुमोदन अनुरोध भेजा गया", "Authorized User" to "अधिकृत उपयोगकर्ता", "Configured Server URL for license authorization & Telegram bot webhook:" to "लाइसेंस प्राधिकरण और Telegram bot webhook के लिए कॉन्फ़िगर सर्वर URL:", "Contact" to "संपर्क", "Contact Number *" to "संपर्क नंबर *", "Copy Device ID" to "डिवाइस आईडी कॉपी करें", "Decoded Output" to "Decoded Output", "Device ID (read-only)" to "डिवाइस आईडी (केवल पढ़ने योग्य)", "Edit Info" to "जानकारी संपादित करें", "Email" to "ईमेल", "Full Name *" to "पूरा नाम *", "License Details" to "लाइसेंस विवरण", "License Server Base URL" to "लाइसेंस सर्वर Base URL", "Lifetime Access" to "लाइफटाइम एक्सेस", "MI Unlock" to "MI Unlock", "Maintenance" to "रखरखाव", "N/A" to "उपलब्ध नहीं", "Original Output" to "Original Output", "Pass Token" to "Pass Token", "Telegram Username" to "Telegram यूज़रनेम", "WhatsApp Number" to "WhatsApp नंबर", "Device Authorized & Active" to "डिवाइस अधिकृत और सक्रिय", "Contact Administrator" to "प्रशासक से संपर्क करें", "Admin Contact" to "प्रशासक संपर्क", "Applicant" to "आवेदक", "MI Unlock Security" to "MI Unlock सुरक्षा", "Invalid License Data" to "लाइसेंस डेटा अमान्य है", "Missing expiration timestamp" to "समाप्ति समय उपलब्ध नहीं है", "Invalid expiration timestamp" to "समाप्ति समय अमान्य है"
    ),
    AppLanguage.AR to mapOf(
        "Active" to "نشط", "Admin approval is required before you can use this application. Please submit your details below." to "موافقة المسؤول مطلوبة لاستخدام التطبيق. أرسل بياناتك أدناه.", "Approval Rejected" to "رُفضت الموافقة", "Approval Request Submitted" to "تم إرسال طلب الموافقة", "Authorized User" to "مستخدم معتمد", "Configured Server URL for license authorization & Telegram bot webhook:" to "عنوان خادم مُعد لتفويض الترخيص وTelegram bot webhook:", "Contact" to "الاتصال", "Contact Number *" to "رقم الاتصال *", "Copy Device ID" to "نسخ معرّف الجهاز", "Decoded Output" to "الإخراج المفكوك", "Device ID (read-only)" to "معرّف الجهاز (للقراءة فقط)", "Edit Info" to "تعديل المعلومات", "Email" to "البريد الإلكتروني", "Full Name *" to "الاسم الكامل *", "License Details" to "تفاصيل الترخيص", "License Server Base URL" to "عنوان الخادم الأساسي للترخيص", "Lifetime Access" to "وصول مدى الحياة", "MI Unlock" to "MI Unlock", "Maintenance" to "الصيانة", "N/A" to "غير متاح", "Original Output" to "الإخراج الأصلي", "Pass Token" to "رمز Pass", "Telegram Username" to "اسم مستخدم Telegram", "WhatsApp Number" to "رقم WhatsApp", "Device Authorized & Active" to "الجهاز مصرح ونشط", "Contact Administrator" to "التواصل مع المسؤول", "Admin Contact" to "اتصال المسؤول", "Applicant" to "المتقدم", "MI Unlock Security" to "أمان MI Unlock", "Invalid License Data" to "بيانات الترخيص غير صالحة", "Missing expiration timestamp" to "وقت الانتهاء مفقود", "Invalid expiration timestamp" to "وقت الانتهاء غير صالح"
    ),
    AppLanguage.UR to mapOf(
        "Active" to "فعال", "Admin approval is required before you can use this application. Please submit your details below." to "اس ایپ کے استعمال سے پہلے ایڈمن کی منظوری ضروری ہے۔ نیچے اپنی معلومات دیں۔", "Approval Rejected" to "منظوری مسترد", "Approval Request Submitted" to "منظوری کی درخواست جمع ہو گئی", "Authorized User" to "منظور شدہ صارف", "Configured Server URL for license authorization & Telegram bot webhook:" to "لائسنس اجازت اور Telegram bot webhook کے لیے کنفیگرڈ سرور URL:", "Contact" to "رابطہ", "Contact Number *" to "رابطہ نمبر *", "Copy Device ID" to "ڈیوائس آئی ڈی کاپی کریں", "Decoded Output" to "Decoded آؤٹ پٹ", "Device ID (read-only)" to "ڈیوائس آئی ڈی (صرف پڑھنے کے لیے)", "Edit Info" to "معلومات میں ترمیم", "Email" to "ای میل", "Full Name *" to "پورا نام *", "License Details" to "لائسنس کی تفصیلات", "License Server Base URL" to "لائسنس سرور Base URL", "Lifetime Access" to "تاحیات رسائی", "MI Unlock" to "MI Unlock", "Maintenance" to "مینٹیننس", "N/A" to "دستیاب نہیں", "Original Output" to "اصل آؤٹ پٹ", "Pass Token" to "Pass Token", "Telegram Username" to "Telegram یوزرنیم", "WhatsApp Number" to "WhatsApp نمبر", "Device Authorized & Active" to "ڈیوائس منظور شدہ اور فعال", "Contact Administrator" to "ایڈمن سے رابطہ کریں", "Admin Contact" to "ایڈمن رابطہ", "Applicant" to "درخواست گزار", "MI Unlock Security" to "MI Unlock سیکیورٹی", "Invalid License Data" to "لائسنس کی معلومات درست نہیں", "Missing expiration timestamp" to "میعاد ختم ہونے کا وقت موجود نہیں", "Invalid expiration timestamp" to "میعاد ختم ہونے کا وقت درست نہیں"
    ),
    AppLanguage.ZH to mapOf(
        "Active" to "已激活", "Admin approval is required before you can use this application. Please submit your details below." to "使用此应用前需要管理员授权。请在下方提交信息。", "Approval Rejected" to "授权被拒绝", "Approval Request Submitted" to "授权申请已提交", "Authorized User" to "授权用户", "Configured Server URL for license authorization & Telegram bot webhook:" to "用于许可证授权和 Telegram bot webhook 的服务器 URL：", "Contact" to "联系方式", "Contact Number *" to "联系电话 *", "Copy Device ID" to "复制设备 ID", "Decoded Output" to "解码输出", "Device ID (read-only)" to "设备 ID（只读）", "Edit Info" to "编辑信息", "Email" to "电子邮件", "Full Name *" to "姓名 *", "License Details" to "许可证详情", "License Server Base URL" to "许可证服务器基础 URL", "Lifetime Access" to "永久访问", "MI Unlock" to "MI Unlock", "Maintenance" to "维护", "N/A" to "不可用", "Original Output" to "原始输出", "Pass Token" to "Pass Token", "Telegram Username" to "Telegram 用户名", "WhatsApp Number" to "WhatsApp 号码", "Device Authorized & Active" to "设备已授权并激活", "Contact Administrator" to "联系管理员", "Admin Contact" to "管理员联系方式", "Applicant" to "申请人", "MI Unlock Security" to "MI Unlock 安全", "Invalid License Data" to "许可证数据无效", "Missing expiration timestamp" to "缺少到期时间", "Invalid expiration timestamp" to "到期时间无效"
    ),
    AppLanguage.TR to mapOf(
        "Active" to "Aktif", "Admin approval is required before you can use this application. Please submit your details below." to "Bu uygulamayı kullanmak için yönetici onayı gerekir. Bilgilerinizi aşağıya gönderin.", "Approval Rejected" to "Onay Reddedildi", "Approval Request Submitted" to "Onay Talebi Gönderildi", "Authorized User" to "Yetkili Kullanıcı", "Configured Server URL for license authorization & Telegram bot webhook:" to "Lisans yetkilendirme ve Telegram bot webhook için yapılandırılmış sunucu URL'si:", "Contact" to "İletişim", "Contact Number *" to "İletişim Numarası *", "Copy Device ID" to "Cihaz Kimliğini Kopyala", "Decoded Output" to "Çözümlenmiş Çıktı", "Device ID (read-only)" to "Cihaz Kimliği (salt okunur)", "Edit Info" to "Bilgileri Düzenle", "Email" to "E-posta", "Full Name *" to "Ad Soyad *", "License Details" to "Lisans Detayları", "License Server Base URL" to "Lisans Sunucusu Base URL", "Lifetime Access" to "Ömür Boyu Erişim", "MI Unlock" to "MI Unlock", "Maintenance" to "Bakım", "N/A" to "Yok", "Original Output" to "Orijinal Çıktı", "Pass Token" to "Pass Token", "Telegram Username" to "Telegram kullanıcı adı", "WhatsApp Number" to "WhatsApp numarası", "Device Authorized & Active" to "Cihaz Yetkili ve Aktif", "Contact Administrator" to "Yöneticiyle İletişim", "Admin Contact" to "Yönetici İletişimi", "Applicant" to "Başvuran", "MI Unlock Security" to "MI Unlock Güvenliği", "Invalid License Data" to "Geçersiz Lisans Verisi", "Missing expiration timestamp" to "Sona erme zamanı eksik", "Invalid expiration timestamp" to "Geçersiz sona erme zamanı"
    ),
    AppLanguage.EN to emptyMap()
)

object AppLocalization {
    private const val PREFS = "mi_unlock_language"
    private const val KEY = "language"
    private val _language = MutableStateFlow(AppLanguage.EN)
    val language: StateFlow<AppLanguage> = _language.asStateFlow()
    fun initialize(context: Context) { val saved = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).getString(KEY, null); _language.value = AppLanguage.entries.firstOrNull { it.code == saved } ?: AppLanguage.EN }
    fun setLanguage(context: Context, language: AppLanguage) { context.getSharedPreferences(PREFS, Context.MODE_PRIVATE).edit().putString(KEY, language.code).apply(); _language.value = language }
    fun text(language: AppLanguage, source: String): String = dictionaries[language]?.get(source) ?: fallbackTranslations[language]?.get(source) ?: extendedTranslations[language]?.get(source) ?: uiTranslations[language]?.get(source) ?: commonErrorTranslations[language]?.get(source) ?: finalTranslations[language]?.get(source) ?: completeTranslations[language]?.get(source) ?: completenessTranslations[language]?.get(source) ?: additionalUiTranslations[language]?.get(source) ?: processingErrorTranslations[language]?.get(source) ?: source
    fun locale(language: AppLanguage): Locale = Locale.forLanguageTag(language.code)
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.EN }

@Composable fun tr(source: String): String = AppLocalization.text(LocalAppLanguage.current, source)
